name: Check Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check-pr:
    name: ❔
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v4
    #   with:
    #     submodules: recursive

    - name: No Merge Commits
      uses: Morishiri/block-merge-commits-action@v1.0.1
      with:
        repo-token: ${{ secrets.READONLY_API_TOKEN }}
